version: "3.7"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka
    expose:
      - "9092"
    environment:
      KAFKA_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_CREATE_TOPICS: "statefun.tasks.demo.requests:1:1,statefun.tasks.demo.actions:1:1,statefun.tasks.demo.events:1:1"
      KAFKA_MESSAGE_MAX_BYTES: 52428800
    depends_on:
      - zookeeper
    restart: unless-stopped

  flink-jobmanager:
    image: example/flink
    build:
      context: .
      dockerfile: flink.Dockerfile
    expose:
      - "6123"
    ports:
      - "8081:8081"
    environment:
      - ROLE=master
      - MASTER_HOST=flink-jobmanager
    depends_on:
      - kafka
    restart: unless-stopped
  
  flink-taskmanager:
    image: example/flink
    build:
      context: .
      dockerfile: flink.Dockerfile
    expose:
      - "6121"
      - "6122"
    depends_on:
      - flink-jobmanager
    links:
      - "flink-jobmanager:flink-jobmanager"
    environment:
      - ROLE=worker
      - MASTER_HOST=flink-jobmanager
    restart: unless-stopped

  demo-app-server:
    image: example/app
    build:
      context: ../demo_app
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - flink-jobmanager
    restart: unless-stopped

  demo-app-worker:
    image: example/app
    build:
      context: ../demo_app
      dockerfile: Dockerfile
    expose:
      - "8085"
    depends_on:
      - flink-jobmanager
    command: worker
    restart: unless-stopped

  demo-app-restricted-worker:
    image: example/app
    build:
      context: ../demo_app
      dockerfile: Dockerfile
    expose:
      - "8085"
    depends_on:
      - flink-jobmanager
    command: "worker inline_tasks_enabled=True"
    environment:
      FLINK_WORKER_NAME: "restricted_worker"
    restart: unless-stopped
